{% set version = "0.1.11" %}

package:
  name: tiledbsoma
  version: {{ version }}

source:
#  url: https://github.com/single-cell-data/TileDB-SOMA/archive/{{ version }}.tar.gz
#  sha256: "845cc7f9c6b9e7d9c2393befb2750df80699338055d9239768df158b3bd0f8a7"
  git_url: https://github.com/single-cell-data/TileDB-SOMA.git
  git_rev: main

build:
  number: 0
  script: python -m pip install apis/python -vv
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.21
    - make
  host:
    - pip
    - pybind11
    - python
    - setuptools
    - setuptools_scm
    - wheel
  run:
    - anndata
    - pandas
    - pyarrow
    - python
    - scanpy
    - scipy
    - tiledb-py

test:
  commands:
    - python -c "import tiledbsoma.libtiledbsoma; print(tiledbsoma.libtiledbsoma.version())"

about:
  home: http://tiledb.com
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'TileDB-SOMA API'
  description: 'Python API for efficient storage and retrieval of single-cell data using TileDB'
  doc_url: https://docs.tiledb.com/
  dev_url: https://github.com/single-cell-data/TileDB-SOMA

extra:
  recipe-maintainers:
    - johnkerl
    - gspowley
    - shelnutt2
