{% set name = "tiledbsoma" %}
{% set version = "2.0.0" %}
{% set sha256 = "TBD" %}
# This is the SHA256 of
#   TileDB-SOMA-i.j.k.tar.gz
# from
#   https://github.com/single-cell-data/TileDB-SOMA/releases/tag/i.j.k
#
# See also build number below.
#
# Also double-check somacore version against TileDB-SOMA's setup.py: this bumps very infrequently
# but it can.

package:
  name: {{ name }}
  version: {{ version }}

## Post-tag real thing:
#source:
#  url: https://github.com/single-cell-data/TileDB-SOMA/archive/{{ version }}.tar.gz
#  sha256: {{ sha256 }}

# Pre-tag canary "will Conda be green if we release":
source:
  git_url: https://github.com/single-cell-data/TileDB-SOMA.git
  # release-2.0.0rc0
  git_rev: c579b340d8ce6e7c9904eb1d6c49c54b0adb6b4a
  git_depth: -1

build:
  number: 0
  skip: true  # [win or linux32 or py2k]
# Important: set this back to 0 on a new release

outputs:
  - name: libtiledbsoma
    version: {{ version }}
    script: build-libtiledbsoma.sh  # [not win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ stdlib("c") }}
        - git
        - cmake
        - make  # [not win]
      host:
        - tiledb >=2.28.0,<2.29
        - spdlog
        - fmt
    about:
      home: http://tiledb.com
      license: MIT
      license_family: MIT
      license_file: LICENSE
      summary: TileDB-SOMA C++ library
      description: >-
        SOMA - for "Stack Of Matrices, Annotated" - is a flexible, extensible,
        and open-source API enabling access to data in a variety of formats. The
        driving use case of SOMA is for single-cell data in the form of
        annotated matrices where observations are frequently cells and features
        are genes, proteins, or genomic regions.
      doc_url: https://docs.tiledb.com/
      dev_url: https://github.com/single-cell-data/TileDB-SOMA
  - name: tiledbsoma-py
    version: {{ version }}
    script: build-tiledbsoma-py.sh
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ stdlib("c") }}
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - pybind11                               # [build_platform != target_platform]
        - pyarrow                                # [build_platform != target_platform]
        - numpy                                  # [build_platform != target_platform]
      host:
        - python
        - pip
        # conda docs say to use pin_subpackage in `run`, but there is no other
        # way to guarantee the locally built package is installed. The pyarrow
        # recipe also does this
        - {{ pin_subpackage('libtiledbsoma', exact=True) }}
        - pybind11
        - setuptools
        - setuptools_scm
        - wheel
        - numpy
        - pyarrow
      run:
        - {{ pin_subpackage('libtiledbsoma', exact=True) }}
        - pandas
        - pyarrow
        - python
        - scipy
        - anndata >=0.10.1
        - typing-extensions >=4.5.0
        - numba >=0.58.1
        - attrs >=22.2
        - somacore ==1.0.29
        - scanpy >=1.9.2
        - more-itertools
    test:
      imports:
        - tiledbsoma
        - tiledbsoma.io
        - tiledbsoma.io.spatial
      requires:
        - pip
        - tiledb-py >=0.34.0,<0.35.0
        # Spatial requirements
        # https://github.com/single-cell-data/TileDB-SOMA/blob/main/apis/python/requirements_spatial.txt
        - geopandas
        - tifffile
        - pillow
        - spatialdata >=0.2.5
        - xarray
        - dask <=2024.11.2
      commands:
        - python -c 'import tiledbsoma; print(tiledbsoma.pytiledbsoma.version())'
        # See also:
        # https://github.com/single-cell-data/TileDB-SOMA/pull/2734
        # https://github.com/single-cell-data/TileDB-SOMA/pull/2692
        # https://github.com/TileDB-Inc/tiledbsoma-feedstock/pull/171
        # https://github.com/apache/arrow/issues/42154
        - python -c 'import tiledbsoma; assert not tiledbsoma.DataFrame.exists("s3://abc/def")'
        - pip check
    about:
      home: http://tiledb.com
      license: MIT
      license_family: MIT
      license_file: LICENSE
      summary: TileDB-SOMA Python API
      description: Python API for efficient storage and retrieval of single-cell data using TileDB
      doc_url: https://docs.tiledb.com/
      dev_url: https://github.com/single-cell-data/TileDB-SOMA/tree/main/apis/python
  - name: r-tiledbsoma
    version: {{ version }}
    script: build-r-tiledbsoma.sh
    build:
      rpaths:
        - lib/R/lib/
        - lib/
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ stdlib("c") }}
        - pkg-config
        # required for cross-compilation
        - cross-r-base {{ r_base }}  # [build_platform != target_platform]
        - r-rcppspdlog >=0.0.20      # [build_platform != target_platform]
        - r-matrix                   # [build_platform != target_platform]
        - r-bit64 >=4.6.0.1          # [build_platform != target_platform]
        - r-rcppint64                # [build_platform != target_platform]
        - r-tiledb >=0.32.0,<0.33    # [build_platform != target_platform]
        - r-arrow                    # [build_platform != target_platform]
        - r-fs                       # [build_platform != target_platform]
        - r-glue                     # [build_platform != target_platform]
        - r-urltools                 # [build_platform != target_platform]
        - r-rcpp                     # [build_platform != target_platform]
        - r-dplyr                    # [build_platform != target_platform]
        - r-data.table               # [build_platform != target_platform]
        - r-rlang                    # [build_platform != target_platform]
        - r-nanoarrow                # [build_platform != target_platform]
      host:
        - {{ pin_subpackage('libtiledbsoma', exact=True) }}
        - r-base
        - r-r6
        - r-matrix
        - r-bit64 >=4.6.0.1
        - r-rcppint64
        - r-tiledb >=0.32.0,<0.33
        - r-arrow
        - r-fs
        - r-glue
        - r-urltools
        - r-rcpp
        - r-dplyr
        - r-data.table
        - r-spdl
        - r-rlang
        - r-nanoarrow
      run:
        - {{ pin_subpackage('libtiledbsoma', exact=True) }}
        - r-base
        - r-r6
        - r-matrix
        - r-bit64 >=4.6.0.1
        - r-tiledb >=0.32.0,<0.33
        - r-arrow
        - r-fs
        - r-glue
        - r-urltools
        - r-rcpp
        - r-dplyr
        - r-data.table
        - r-spdl
        - r-rlang
        - r-nanoarrow
    test:
      requires:
        - cctools  # [osx]
        - r-iterators
        - r-itertools
        - r-jsonlite
        - r-seuratobject >= 4.1.0
        - r-testthat >=3.0.0
        - r-withr
        - r-tibble
      source_files:
        - apis/r/tests/
      commands:
        - $R -e "library('tiledbsoma')"
        - $R -e "tiledbsoma::show_package_versions()"
        - "ldd $PREFIX/lib/R/library/tiledbsoma/libs/tiledbsoma.so | grep -e libR -e libtiledb"  # [linux]
        # r-base-feedstock updated SHLIB_EXT from .dylib to .so on macOS between R 4.3 and 4.4
        - "otool -L $PREFIX/lib/R/library/tiledbsoma/libs/tiledbsoma.dylib | grep -e libR -e libtiledb"  # [osx and r_base == "4.3"]
        - "otool -L $PREFIX/lib/R/library/tiledbsoma/libs/tiledbsoma.so    | grep -e libR -e libtiledb"  # [osx and r_base != "4.3"]
        # Run testthat tests
        - $R -e "testthat::test_file('apis/r/tests/testthat.R', stop_on_failure = TRUE)"
    about:
      home: http://tiledb.com
      license: MIT
      license_family: MIT
      license_file:
        - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
        - apis/r/LICENSE
      summary: TileDB-SOMA R API
      description: R API for efficient storage and retrieval of single-cell data using TileDB
      doc_url: https://docs.tiledb.com/
      dev_url: https://github.com/single-cell-data/TileDB-SOMA/tree/main/apis/r

about:
  home: http://tiledb.com
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: TileDB-SOMA API
  description: Efficient storage and retrieval of single-cell data using TileDB
  doc_url: https://docs.tiledb.com/
  dev_url: https://github.com/single-cell-data/TileDB-SOMA

extra:
  recipe-maintainers:
    - shelnutt2
    - mlin
    - jdblischak
    - jp-dark
    - ihnorton
