{% set name = "tiledbsoma" %}
{% set version = "1.8.0" %}
{% set sha256 = "tbd" %}
# This is the SHA256 of
#   TileDB-SOMA-i.j.k.tar.gz
# from
#   https://github.com/single-cell-data/TileDB-SOMA/releases/tag/i.j.k
#
# See also build number below

package:
  name: {{ name }}
  version: {{ version }}

# Post-tag real thing:
#source:
#  url: https://github.com/single-cell-data/TileDB-SOMA/archive/{{ version }}.tar.gz
#  sha256: {{ sha256 }}

# Pre-tag canary "will Conda be green if we release":
source:
  git_url: https://github.com/single-cell-data/TileDB-SOMA.git
  git_rev: 5bf75f5d5373933265c97bf1e430b01272099080
  git_depth: -1
  # hoping to be 1.8.0 <-- FILL IN HERE


build:
  number: 0
  skip: true  # [win or linux32 or py2k]
# Important: set this back to 0 on a new release

outputs:
  - name: libtiledbsoma
    version: {{ version }}
    script: build-libtiledbsoma.sh  # [not win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - git
        - cmake
        - make  # [not win]
      host:
        - tiledb >=2.20.0,<2.21
        - spdlog
        - fmt
        #### TEMP - libgoogle-cloud 2.17.*
      run:
        # https://conda-forge.org/docs/maintainer/knowledge_base/#requiring-newer-macos-sdks
        - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]
    about:
      home: http://tiledb.com
      license: MIT
      license_family: MIT
      license_file: LICENSE
      summary: TileDB-SOMA C++ library
      description: >-
        SOMA - for "Stack Of Matrices, Annotated" - is a flexible, extensible,
        and open-source API enabling access to data in a variety of formats. The
        driving use case of SOMA is for single-cell data in the form of
        annotated matrices where observations are frequently cells and features
        are genes, proteins, or genomic regions.
      doc_url: https://docs.tiledb.com/
      dev_url: https://github.com/single-cell-data/TileDB-SOMA
  - name: tiledbsoma-py
    version: {{ version }}
    script: build-tiledbsoma-py.sh
    build:
    requirements:
      build:
        - {{ compiler('cxx') }}
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - pybind11                               # [build_platform != target_platform]
        # https://github.com/single-cell-data/TileDB-SOMA/issues/1926
        - pyarrow <13.0                          # [build_platform != target_platform and osx]
        - pyarrow                                # [build_platform != target_platform and not osx]
        - pyarrow-hotfix                         # [build_platform != target_platform]
        - numpy                                  # [build_platform != target_platform]
      host:
        - python
        - pip
        # conda docs say to use pin_subpackage in `run`, but there is no other
        # way to guarantee the locally built package is installed. The pyarrow
        # recipe also does this
        - {{ pin_subpackage('libtiledbsoma', exact=True) }}
        - pybind11
        - setuptools
        - setuptools_scm
        - wheel
        - numpy
        # https://github.com/single-cell-data/TileDB-SOMA/issues/1926
        - pyarrow <13.0 # [osx]
        - pyarrow       # [not osx]
        - pyarrow-hotfix
        #### TEMP - libgoogle-cloud 2.17.*
      run:
        - {{ pin_compatible('numpy', lower_bound='1.16', upper_bound='1.24') }}
        - {{ pin_subpackage('libtiledbsoma', exact=True) }}
        - pandas
        # https://github.com/single-cell-data/TileDB-SOMA/issues/1926
        - pyarrow <13.0 # [osx]
        - pyarrow       # [not osx]
        - pyarrow-hotfix
        - python
        - scipy
        - anndata       # [py>37]
        - anndata <0.9  # [py<=37]
        - tiledb-py >=0.26.0,<0.27.0
        - typing-extensions >=4.1
        - numba >=0.58.1 # [py>37]
        - numba          # [py<=37]
        - attrs >=22.2
        - somacore >=1.0.8
        - scanpy >=1.9.2
        # https://conda-forge.org/docs/maintainer/knowledge_base/#requiring-newer-macos-sdks
        - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]
    test:
      imports:
        - tiledbsoma
      commands:
        - python -c "import tiledbsoma; print(tiledbsoma.pytiledbsoma.version())"
    about:
      home: http://tiledb.com
      license: MIT
      license_family: MIT
      license_file: LICENSE
      summary: TileDB-SOMA Python API
      description: Python API for efficient storage and retrieval of single-cell data using TileDB
      doc_url: https://docs.tiledb.com/
      dev_url: https://github.com/single-cell-data/TileDB-SOMA/tree/main/apis/python
  - name: r-tiledbsoma
    version: {{ version }}
    script: build-r-tiledbsoma.sh
    build:
      rpaths:
        - lib/R/lib/
        - lib/
    requirements:
      build:
        - {{ compiler('cxx') }}
        - pkg-config
        # required for cross-compilation
        - cross-r-base {{ r_base }}  # [build_platform != target_platform]
        - r-rcppspdlog               # [build_platform != target_platform]
        - r-matrix                   # [build_platform != target_platform]
        - r-bit64                    # [build_platform != target_platform]
        - r-rcppint64                # [build_platform != target_platform]
        - r-tiledb >=0.24.0,<0.25    # [build_platform != target_platform]
        - r-arrow                    # [build_platform != target_platform]
        - r-fs                       # [build_platform != target_platform]
        - r-glue                     # [build_platform != target_platform]
        - r-urltools                 # [build_platform != target_platform]
        - r-rcpp                     # [build_platform != target_platform]
        - r-dplyr                    # [build_platform != target_platform]
        - r-data.table               # [build_platform != target_platform]
        - r-rlang                    # [build_platform != target_platform]
        # https://conda-forge.org/docs/maintainer/knowledge_base/#requiring-newer-macos-sdks
        - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]
      host:
        - {{ pin_subpackage('libtiledbsoma', exact=True) }}
        - r-base
        - r-r6
        - r-matrix
        - r-bit64
        - r-rcppint64
        - r-tiledb >=0.24.0,<0.25
        - r-arrow
        - r-fs
        - r-glue
        - r-urltools
        - r-rcpp
        - r-dplyr
        - r-data.table
        - r-spdl
        - r-rlang
      run:
        - {{ pin_subpackage('libtiledbsoma', exact=True) }}
        - r-base
        - r-r6
        - r-matrix
        - r-bit64
        - r-tiledb >=0.24.0,<0.25
        - r-arrow
        - r-fs
        - r-glue
        - r-urltools
        - r-rcpp
        - r-dplyr
        - r-data.table
        - r-spdl
        - r-rlang
    test:
      commands:
        - $R -e "library('tiledbsoma')"
        - $R -e "tiledbsoma::show_package_versions()"
        - "otool -L $PREFIX/lib/R/library/tiledbsoma/libs/tiledbsoma.dylib | grep -e libR -e libtiledb"  # [osx]
        - "ldd $PREFIX/lib/R/library/tiledbsoma/libs/tiledbsoma.so | grep -e libR -e libtiledb"  # [linux]
    about:
      home: http://tiledb.com
      license: MIT
      license_family: MIT
      license_file:
        - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
        - apis/r/LICENSE
      summary: TileDB-SOMA R API
      description: R API for efficient storage and retrieval of single-cell data using TileDB
      doc_url: https://docs.tiledb.com/
      dev_url: https://github.com/single-cell-data/TileDB-SOMA/tree/main/apis/r

about:
  home: http://tiledb.com
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: TileDB-SOMA API
  description: Efficient storage and retrieval of single-cell data using TileDB
  doc_url: https://docs.tiledb.com/
  dev_url: https://github.com/single-cell-data/TileDB-SOMA

extra:
  recipe-maintainers:
    - johnkerl
    - gspowley
    - shelnutt2
    - mlin
    - jdblischak
