{% set name = "tiledbsoma" %}
{% set version = "1.2.4" %}
{% set version_r = "0.0.0.9024" %}
{% set sha256 = "3b1cdfb5b1a9572c191c30cbab8c11d2344d3d6015dbc45cb4e66eca8ab2eb54" %}
# This is the SHA256 of
#   TileDB-SOMA-i.j.k.tar.gz
# from
#   https://github.com/single-cell-data/TileDB-SOMA/releases/tag/i.j.k
#
# See also build number below

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/single-cell-data/TileDB-SOMA/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}
# Pre-release canary "will Conda be green if we release":
#source:
#  git_url: https://github.com/single-cell-data/TileDB-SOMA.git
#  git_rev: db2782bad8b11f7eb0899d0a8b78118c6b5a49a2
#  git_depth: 1
#  # hoping to be 1.2.4


build:
  number: 0
  skip: true  # [win or linux32 or py2k]
# Important: set this back to 0 on a new release

outputs:
  - name: libtiledbsoma
    version: {{ version }}
    script: build-libtiledbsoma.sh  # [not win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - git
        - cmake
        - make  # [not win]
      host:
        - tiledb >=2.15.2,<2.16
        - spdlog
        - fmt
      run:
        - tiledb >=2.15.2,<2.16
        - spdlog
        - fmt
  - name: tiledbsoma-py
    version: {{ version }}
    script: build-tiledbsoma-py.sh
    build:
    requirements:
      build:
        - {{ compiler('cxx') }}
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - pybind11                               # [build_platform != target_platform]
        - pyarrow 9.0.*                          # [build_platform != target_platform]
        - numpy                                  # [build_platform != target_platform]
      host:
        - python
        - pip
        # conda docs say to use pin_subpackage in `run`, but there is no other
        # way to guarantee the locally built package is installed. The pyarrow
        # recipe also does this
        - {{ pin_subpackage('libtiledbsoma', exact=True) }}
        - pybind11
        - setuptools
        - setuptools_scm
        - wheel
        - numpy
        - pyarrow 9.0.*
      run:
        - {{ pin_compatible('numpy', lower_bound='1.16', upper_bound='1.24') }}
        - {{ pin_subpackage('libtiledbsoma', exact=True) }}
        - pandas
        - pyarrow 9.0.*
        - python
        - scipy
        - anndata       # [py>37]
        - anndata <0.9  # [py<=37]
        - tiledb-py >=0.21.3,<0.22.0
        - typing-extensions
        - numba
        - attrs
        - somacore 1.0.*
        - scanpy 1.9.*
    test:
      imports:
        - tiledbsoma
      commands:
        - python -c "import tiledbsoma; print(tiledbsoma.pytiledbsoma.version())"
  - name: r-tiledbsoma
    version: {{ version_r }}
    script: build-r-tiledbsoma.sh
    build:
      rpaths:
        - lib/R/lib/
        - lib/
    requirements:
      build:
        - {{ compiler('cxx') }}
        - pkg-config
        # required for cross-compilation
        - cross-r-base {{ r_base }}  # [build_platform != target_platform]
        - r-rcppspdlog               # [build_platform != target_platform]
        - r-matrix                   # [build_platform != target_platform]
        - r-bit64                    # [build_platform != target_platform]
        - r-tiledb >=0.19.1          # [build_platform != target_platform]
        - r-arrow                    # [build_platform != target_platform]
        - r-fs                       # [build_platform != target_platform]
        - r-glue                     # [build_platform != target_platform]
        - r-urltools                 # [build_platform != target_platform]
        - r-rcpp                     # [build_platform != target_platform]
        - r-dplyr                    # [build_platform != target_platform]
        - r-data.table               # [build_platform != target_platform]
        - r-rlang                    # [build_platform != target_platform]
      host:
        - {{ pin_subpackage('libtiledbsoma', exact=True) }}
        - r-base
        - r-r6
        - r-matrix
        - r-bit64
        - r-tiledb >=0.19.1
        - r-arrow
        - r-fs
        - r-glue
        - r-urltools
        - r-rcpp
        - r-dplyr
        - r-data.table
        - r-spdl
        - r-rlang
      run:
        - {{ pin_subpackage('libtiledbsoma', exact=True) }}
        - r-base
        - r-r6
        - r-matrix
        - r-bit64
        - r-tiledb >=0.19.1
        - r-arrow
        - r-fs
        - r-glue
        - r-urltools
        - r-rcpp
        - r-dplyr
        - r-data.table
        - r-spdl
        - r-rlang
    test:
      commands:
        - $R -e "library('tiledbsoma')"
        - $R -e "tiledbsoma::show_package_versions()"
        - "otool -L $PREFIX/lib/R/library/tiledbsoma/libs/tiledbsoma.dylib | grep -e libR -e libtiledb"  # [osx]
        - "ldd $PREFIX/lib/R/library/tiledbsoma/libs/tiledbsoma.so | grep -e libR -e libtiledb"  # [linux]

about:
  home: http://tiledb.com
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'TileDB-SOMA API'
  description: 'Python API for efficient storage and retrieval of single-cell data using TileDB'
  doc_url: https://docs.tiledb.com/
  dev_url: https://github.com/single-cell-data/TileDB-SOMA

extra:
  recipe-maintainers:
    - johnkerl
    - gspowley
    - shelnutt2
    - mlin
    - jdblischak
