{% set name = "tiledbsoma" %}
{% set version = "0.5.0a2" %}
{% set sha256 = "217652ad87b0ef448460597d589342d5850c653afabc5fa939cd32b787a5e9ba" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/single-cell-data/TileDB-SOMA/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install . -vv
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.21
    - make
  host:
    - pip
    - pybind11
    - python
    - setuptools
    - setuptools_scm
    - wheel
  run:
    - anndata
    - pandas
    - pyarrow
    - python
    - scanpy
    - scipy
    - tiledb-py

test:
  commands:
    - python -c "import tiledbsoma.libtiledbsoma; print(tiledbsoma.libtiledbsoma.version())"

about:
  home: http://tiledb.com
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'TileDB-SOMA API'
  description: 'Python API for efficient storage and retrieval of single-cell data using TileDB'
  doc_url: https://docs.tiledb.com/
  dev_url: https://github.com/single-cell-data/TileDB-SOMA

extra:
  recipe-maintainers:
    - johnkerl
    - gspowley
    - shelnutt2
    - mlin
