{% set name = "tiledbsoma" %}
{% set version = "1.2.1" %}
{% set sha256 = "3048e3aabb94e5cd3b7904de59e15fe0eb117b2e04bbcf1bc6ee21e491fef0c2" %}



package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/single-cell-data/TileDB-SOMA/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [win or linux32 or py2k]

outputs:
  - name: libtiledbsoma
    version: {{ version }}
    script: build-libtiledbsoma.sh  # [not win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - git
        - cmake
        - make  # [not win]
      host:
        - tiledb 2.15.*
        - spdlog
        - fmt
      run:
        - tiledb 2.15.*
        - spdlog
        - fmt
  - name: tiledbsoma-py
    version: {{ version }}
    script: build-tiledbsoma-py.sh
    build:
    requirements:
      build:
        - {{ compiler('cxx') }}
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - pybind11                               # [build_platform != target_platform]
        - pyarrow 9.0.*                          # [build_platform != target_platform]
        - numpy                                  # [build_platform != target_platform]
      host:
        - python
        - pip
        - libtiledbsoma {{ version }}
        - pybind11
        - setuptools
        - setuptools_scm
        - wheel
        - numpy
        - pyarrow 9.0.*
      run:
        - {{ pin_compatible('numpy', lower_bound='1.16', upper_bound='1.24') }}
        - {{ pin_subpackage('libtiledbsoma', exact=True) }}
        - pandas
        - pyarrow 9.0.*
        - python
        - scipy
        - anndata       # [py>37]
        - anndata <0.9  # [py<=37]
        - tiledb-py 0.21.*
        - typing-extensions
        - numba
        - attrs
        - somacore 1.0.*
        - scanpy 1.9.*
    test:
      imports:
        - tiledbsoma
      commands:
        - python -c "import tiledbsoma; print(tiledbsoma.pytiledbsoma.version())"

about:
  home: http://tiledb.com
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'TileDB-SOMA API'
  description: 'Python API for efficient storage and retrieval of single-cell data using TileDB'
  doc_url: https://docs.tiledb.com/
  dev_url: https://github.com/single-cell-data/TileDB-SOMA

extra:
  recipe-maintainers:
    - johnkerl
    - gspowley
    - shelnutt2
    - mlin
    - jdblischak
