github:
  user_or_org: TileDB-Inc
  branch_name: main
  tooling_branch_name: main
build_platform:
  osx_arm64: osx_64
conda_forge_output_validation: false
test: native_and_emulated
upload_on_branch: nightly-build
azure:
  build_id: 43
  user_or_org: TileDB-Inc
  project_name: CI
