github:
  user_or_org: TileDB-Inc
  # FOR THIS PR ONLY
  # branch_name: main
  branch_name: dev
  store_build_artifacts: true
  tooling_branch_name: main
build_platform:
  linux_aarch64: linux_64
  osx_arm64: osx_64
conda_forge_output_validation: true
test: native_and_emulated
# build_with_mambabuild: false
# FOR THIS PR
# upload_on_branch: main
upload_on_branch: dev
azure:
  build_id: 43
  user_or_org: TileDB-Inc
  project_name: CI
channel_priority: flexible
provider:
  linux_aarch64: default
