# - only affects README installation instructions
# - edit recipe/conda_build_config.yaml to affect build
channels:
  targets:
    - ["tiledb", "main"]
github:
  user_or_org: TileDB-Inc
  branch_name: main
  tooling_branch_name: main
build_platform:
  osx_arm64: osx_64
conda_forge_output_validation: true
test_on_native_only: true
# build_with_mambabuild: false
upload_on_branch: main
azure:
  build_id: 43
  user_or_org: TileDB-Inc
  project_name: CI
