github:
  user_or_org: TileDB-Inc
  branch_name: main
  tooling_branch_name: main
build_platform:
  linux_aarch64: linux_64
  osx_arm64: osx_64
conda_forge_output_validation: true
test: native_and_emulated
# build_with_mambabuild: false
upload_on_branch: main
azure:
  build_id: 43
  user_or_org: TileDB-Inc
  project_name: CI
channel_priority: flexible
provider:
  linux_aarch64: default
